QT += core gui widgets network xml webenginecore webenginewidgets

CONFIG += c++20 console warn_on object_parallel_to_source
TEMPLATE = app
TARGET = safe-exam-browser

QMAKE_CXXFLAGS += -Wall -Wextra -Wpedantic

INCLUDEPATH += src
LIBS += -lz -lcrypto

OBJECTS_DIR = $$OUT_PWD/.obj
MOC_DIR = $$OUT_PWD/.moc
RCC_DIR = $$OUT_PWD/.rcc
UI_DIR = $$OUT_PWD/.ui
DESTDIR = $$OUT_PWD/bin

SOURCES += \
    src/applications/application_factory.cpp \
    src/applications/application_manager.cpp \
    src/applications/application_window.cpp \
    src/applications/external_application.cpp \
    src/applications/external_application_instance.cpp \
    src/client/client_controller.cpp \
    src/client/composition_root.cpp \
    src/client/coordinator.cpp \
    src/client/notifications/about_notification.cpp \
    src/client/notifications/log_notification.cpp \
    src/client/notifications/verificator_notification.cpp \
    src/client/operations/application_operation.cpp \
    src/client/operations/browser_operation.cpp \
    src/client/operations/client_operation.cpp \
    src/client/operations/client_operation_sequence.cpp \
    src/client/operations/shell_operation.cpp \
    src/client/responsibilities/browser_responsibility.cpp \
    src/client/responsibilities/client_responsibility.cpp \
    src/client/responsibilities/shell_responsibility.cpp \
    src/communication/hosts/base_host.cpp \
    src/communication/hosts/host_object_factory.cpp \
    src/communication/proxies/base_proxy.cpp \
    src/communication/proxies/client_proxy.cpp \
    src/communication/proxies/proxy_factory.cpp \
    src/communication/proxies/proxy_object_factory.cpp \
    src/communication/proxies/runtime_proxy.cpp \
    src/communication/proxies/service_proxy.cpp \
    src/configuration/configuration_data/data_mapper.cpp \
    src/configuration/configuration_data/data_processor.cpp \
    src/configuration/configuration_data/data_values.cpp \
    src/configuration/configuration_data/data_mapping/application_data_mapper.cpp \
    src/configuration/configuration_data/data_mapping/audio_data_mapper.cpp \
    src/configuration/configuration_data/data_mapping/base_data_mapper.cpp \
    src/configuration/configuration_data/data_mapping/browser_data_mapper.cpp \
    src/configuration/configuration_data/data_mapping/configuration_file_data_mapper.cpp \
    src/configuration/configuration_data/data_mapping/display_data_mapper.cpp \
    src/configuration/configuration_data/data_mapping/general_data_mapper.cpp \
    src/configuration/configuration_data/data_mapping/input_data_mapper.cpp \
    src/configuration/configuration_data/data_mapping/proctoring_data_mapper.cpp \
    src/configuration/configuration_data/data_mapping/security_data_mapper.cpp \
    src/configuration/configuration_data/data_mapping/server_data_mapper.cpp \
    src/configuration/configuration_data/data_mapping/service_data_mapper.cpp \
    src/configuration/configuration_data/data_mapping/system_data_mapper.cpp \
    src/configuration/configuration_data/data_mapping/user_interface_data_mapper.cpp \
    src/configuration/configuration_data/json.cpp \
    src/configuration/configuration_repository.cpp \
    src/configuration/cryptography/certificate_store.cpp \
    src/configuration/cryptography/hash_algorithm.cpp \
    src/configuration/cryptography/key_generator.cpp \
    src/configuration/cryptography/password_encryption.cpp \
    src/configuration/cryptography/public_key_encryption.cpp \
    src/configuration/cryptography/public_key_symmetric_encryption.cpp \
    src/configuration/data_compression/gzip_compressor.cpp \
    src/configuration/data_formats/binary_block.cpp \
    src/configuration/data_formats/binary_parser.cpp \
    src/configuration/data_formats/binary_serializer.cpp \
    src/configuration/data_formats/xml_element.cpp \
    src/configuration/data_formats/xml_parser.cpp \
    src/configuration/data_formats/xml_serializer.cpp \
    src/configuration/data_resources/file_resource_loader.cpp \
    src/configuration/data_resources/file_resource_saver.cpp \
    src/configuration/data_resources/network_resource_loader.cpp \
    src/configuration/sub_stream.cpp \
    src/browser/BrowserApplication.cpp \
    src/browser/BrowserControl.cpp \
    src/browser/BrowserWindow.cpp \
    src/browser/Clipboard.cpp \
    src/browser/content/ContentLoader.cpp \
    src/browser/filters/RequestFilter.cpp \
    src/browser/filters/RuleFactory.cpp \
    src/browser/filters/rules/RegexRule.cpp \
    src/browser/filters/rules/SimplifiedRule.cpp \
    src/browser/engine/qtwebengine_browser_view.cpp \
    src/browser/engine/wpe_browser_view.cpp \
    src/browser/memory_pressure_monitor.cpp \
    src/browser/key_generator.cpp \
    src/browser/request_filter.cpp \
    src/browser/request_interceptor.cpp \
    src/browser/webengine_environment.cpp \
    src/app_controller.cpp \
    src/main.cpp \
    src/settings/password_container.cpp \
    src/settings/resource_loader.cpp \
    src/settings/settings_defaults.cpp \
    src/settings/settings_mapping.cpp \
    src/settings/settings_parsing.cpp \
    src/shell/taskbar/taskbar_service.cpp \
    src/shell/taskbar/platform/audio_controller.cpp \
    src/shell/taskbar/platform/battery_controller.cpp \
    src/shell/taskbar/platform/command_helper.cpp \
    src/shell/taskbar/platform/keyboard_controller.cpp \
    src/shell/taskbar/platform/network_controller.cpp \
    src/ui/taskbar/common/taskbar_button.cpp \
    src/ui/taskbar/common/taskbar_popup.cpp \
    src/ui/taskbar/controls/application_control.cpp \
    src/ui/taskbar/controls/audio_control.cpp \
    src/ui/taskbar/controls/battery_control.cpp \
    src/ui/taskbar/controls/clock_widget.cpp \
    src/ui/taskbar/controls/external_application_control.cpp \
    src/ui/taskbar/controls/keyboard_control.cpp \
    src/ui/taskbar/controls/network_control.cpp \
    src/ui/taskbar/controls/notification_control.cpp \
    src/ui/taskbar/controls/raise_hand_control.cpp \
    src/ui/taskbar/controls/window_list_popup.cpp \
    src/ui/taskbar/taskbar_widget.cpp \
    src/ui/runtime_window.cpp \
    src/ui/seb_taskbar.cpp \
    src/seb_settings.cpp \
    src/seb_session.cpp \
    src/browser_window.cpp

HEADERS += \
    src/app_controller.h \
    src/applications/application_factory.h \
    src/applications/application_manager.h \
    src/applications/application_window.h \
    src/applications/contracts/Properties/AssemblyInfo.h \
    src/applications/contracts/application.h \
    src/applications/contracts/application_factory.h \
    src/applications/contracts/application_window.h \
    src/applications/contracts/events/icon_changed_event_handler.h \
    src/applications/contracts/events/title_changed_event_handler.h \
    src/applications/contracts/events/windows_changed_event_handler.h \
    src/applications/contracts/factory_result.h \
    src/applications/external_application.h \
    src/applications/external_application_instance.h \
    src/client/client_context.h \
    src/client/client_controller.h \
    src/client/composition_root.h \
    src/client/contracts/coordinator.h \
    src/client/coordinator.h \
    src/client/notifications/about_notification.h \
    src/client/notifications/log_notification.h \
    src/client/notifications/verificator_notification.h \
    src/client/operations/application_operation.h \
    src/client/operations/browser_operation.h \
    src/client/operations/client_operation.h \
    src/client/operations/client_operation_sequence.h \
    src/client/operations/shell_operation.h \
    src/client/responsibilities/browser_responsibility.h \
    src/client/responsibilities/client_responsibility.h \
    src/client/responsibilities/client_task.h \
    src/client/responsibilities/shell_responsibility.h \
    src/communication/Properties/AssemblyInfo.h \
    src/communication/contracts/Properties/AssemblyInfo.h \
    src/communication/contracts/data/authentication_response.h \
    src/communication/contracts/data/configuration_response.h \
    src/communication/contracts/data/connection_response.h \
    src/communication/contracts/data/disconnection_message.h \
    src/communication/contracts/data/disconnection_response.h \
    src/communication/contracts/data/exam_selection_reply_message.h \
    src/communication/contracts/data/exam_selection_request_message.h \
    src/communication/contracts/data/message.h \
    src/communication/contracts/data/message_box_reply_message.h \
    src/communication/contracts/data/message_box_request_message.h \
    src/communication/contracts/data/password_reply_message.h \
    src/communication/contracts/data/password_request_message.h \
    src/communication/contracts/data/password_request_purpose.h \
    src/communication/contracts/data/reconfiguration_denied_message.h \
    src/communication/contracts/data/reconfiguration_message.h \
    src/communication/contracts/data/response.h \
    src/communication/contracts/data/server_failure_action_reply_message.h \
    src/communication/contracts/data/server_failure_action_request_message.h \
    src/communication/contracts/data/session_start_message.h \
    src/communication/contracts/data/session_stop_message.h \
    src/communication/contracts/data/simple_message.h \
    src/communication/contracts/data/simple_message_purport.h \
    src/communication/contracts/data/simple_response.h \
    src/communication/contracts/data/simple_response_purport.h \
    src/communication/contracts/events/client_configuration_event_args.h \
    src/communication/contracts/events/communication_event_args.h \
    src/communication/contracts/events/communication_event_handler.h \
    src/communication/contracts/events/exam_selection_reply_event_args.h \
    src/communication/contracts/events/exam_selection_request_event_args.h \
    src/communication/contracts/events/message_box_reply_event_args.h \
    src/communication/contracts/events/message_box_request_event_args.h \
    src/communication/contracts/events/password_reply_event_args.h \
    src/communication/contracts/events/password_request_event_args.h \
    src/communication/contracts/events/reconfiguration_event_args.h \
    src/communication/contracts/events/server_failure_action_reply_event_args.h \
    src/communication/contracts/events/server_failure_action_request_event_args.h \
    src/communication/contracts/events/session_start_event_args.h \
    src/communication/contracts/events/session_stop_event_args.h \
    src/communication/contracts/hosts/i_client_host.h \
    src/communication/contracts/hosts/i_host_object.h \
    src/communication/contracts/hosts/i_host_object_factory.h \
    src/communication/contracts/hosts/i_runtime_host.h \
    src/communication/contracts/hosts/i_service_host.h \
    src/communication/contracts/i_communication.h \
    src/communication/contracts/i_communication_host.h \
    src/communication/contracts/i_communication_proxy.h \
    src/communication/contracts/interlocutor.h \
    src/communication/contracts/proxies/communication_result.h \
    src/communication/contracts/proxies/i_client_proxy.h \
    src/communication/contracts/proxies/i_proxy_factory.h \
    src/communication/contracts/proxies/i_proxy_object.h \
    src/communication/contracts/proxies/i_proxy_object_factory.h \
    src/communication/contracts/proxies/i_runtime_proxy.h \
    src/communication/contracts/proxies/i_service_proxy.h \
    src/communication/hosts/base_host.h \
    src/communication/hosts/host_object_factory.h \
    src/communication/proxies/base_proxy.h \
    src/communication/proxies/client_proxy.h \
    src/communication/proxies/proxy_factory.h \
    src/communication/proxies/proxy_object_factory.h \
    src/communication/proxies/runtime_proxy.h \
    src/communication/proxies/service_proxy.h \
    src/configuration/Properties/AssemblyInfo.h \
    src/configuration/configuration_data/data_mapper.h \
    src/configuration/configuration_data/data_processor.h \
    src/configuration/configuration_data/data_values.h \
    src/configuration/configuration_data/data_mapping/application_data_mapper.h \
    src/configuration/configuration_data/data_mapping/audio_data_mapper.h \
    src/configuration/configuration_data/data_mapping/base_data_mapper.h \
    src/configuration/configuration_data/data_mapping/browser_data_mapper.h \
    src/configuration/configuration_data/data_mapping/configuration_file_data_mapper.h \
    src/configuration/configuration_data/data_mapping/display_data_mapper.h \
    src/configuration/configuration_data/data_mapping/general_data_mapper.h \
    src/configuration/configuration_data/data_mapping/input_data_mapper.h \
    src/configuration/configuration_data/data_mapping/proctoring_data_mapper.h \
    src/configuration/configuration_data/data_mapping/security_data_mapper.h \
    src/configuration/configuration_data/data_mapping/server_data_mapper.h \
    src/configuration/configuration_data/data_mapping/service_data_mapper.h \
    src/configuration/configuration_data/data_mapping/system_data_mapper.h \
    src/configuration/configuration_data/data_mapping/user_interface_data_mapper.h \
    src/configuration/configuration_data/json.h \
    src/configuration/configuration_data/keys.h \
    src/configuration/configuration_repository.h \
    src/configuration/contracts/Properties/AssemblyInfo.h \
    src/configuration/contracts/app_config.h \
    src/configuration/contracts/client_configuration.h \
    src/configuration/contracts/cryptography/encryption_parameters.h \
    src/configuration/contracts/cryptography/i_certificate_store.h \
    src/configuration/contracts/cryptography/i_hash_algorithm.h \
    src/configuration/contracts/cryptography/i_key_generator.h \
    src/configuration/contracts/cryptography/i_password_encryption.h \
    src/configuration/contracts/cryptography/i_public_key_encryption.h \
    src/configuration/contracts/cryptography/password_parameters.h \
    src/configuration/contracts/cryptography/public_key_parameters.h \
    src/configuration/contracts/data_compression/i_data_compressor.h \
    src/configuration/contracts/data_formats/format_type.h \
    src/configuration/contracts/data_formats/i_data_parser.h \
    src/configuration/contracts/data_formats/i_data_serializer.h \
    src/configuration/contracts/data_formats/parse_result.h \
    src/configuration/contracts/data_formats/serialize_result.h \
    src/configuration/contracts/data_resources/i_resource_loader.h \
    src/configuration/contracts/data_resources/i_resource_saver.h \
    src/configuration/contracts/i_configuration_repository.h \
    src/configuration/contracts/load_status.h \
    src/configuration/contracts/save_status.h \
    src/configuration/contracts/service_configuration.h \
    src/configuration/contracts/session_configuration.h \
    src/configuration/cryptography/certificate_store.h \
    src/configuration/cryptography/hash_algorithm.h \
    src/configuration/cryptography/key_generator.h \
    src/configuration/cryptography/password_encryption.h \
    src/configuration/cryptography/public_key_encryption.h \
    src/configuration/cryptography/public_key_symmetric_encryption.h \
    src/configuration/data_compression/gzip_compressor.h \
    src/configuration/data_formats/binary_block.h \
    src/configuration/data_formats/binary_parser.h \
    src/configuration/data_formats/binary_serializer.h \
    src/configuration/data_formats/xml_element.h \
    src/configuration/data_formats/xml_parser.h \
    src/configuration/data_formats/xml_serializer.h \
    src/configuration/data_resources/file_resource_loader.h \
    src/configuration/data_resources/file_resource_saver.h \
    src/configuration/data_resources/network_resource_loader.h \
    src/configuration/sub_stream.h \
    src/browser/BrowserApplication.h \
    src/browser/BrowserApplicationContext.h \
    src/browser/BrowserControl.h \
    src/browser/BrowserIconResource.h \
    src/browser/BrowserWindow.h \
    src/browser/BrowserWindowContext.h \
    src/browser/Clipboard.h \
    src/browser/Properties/AssemblyInfo.h \
    src/browser/contracts/IBrowserApplication.h \
    src/browser/contracts/IBrowserWindow.h \
    src/browser/contracts/Properties/AssemblyInfo.h \
    src/browser/contracts/events/download_event_args.h \
    src/browser/contracts/events/download_finished_callback.h \
    src/browser/contracts/events/download_requested_event_handler.h \
    src/browser/contracts/events/lose_focus_requested_event_handler.h \
    src/browser/contracts/events/tab_pressed_event_handler.h \
    src/browser/contracts/events/termination_requested_event_handler.h \
    src/browser/contracts/events/user_identifier_detected_event_handler.h \
    src/browser/contracts/filters/IRequestFilter.h \
    src/browser/contracts/filters/IRule.h \
    src/browser/contracts/filters/IRuleFactory.h \
    src/browser/contracts/filters/request.h \
    src/browser/content/ContentLoader.h \
    src/browser/events/clipboard_changed_event_handler.h \
    src/browser/events/dialog_requested_event_args.h \
    src/browser/events/dialog_requested_event_handler.h \
    src/browser/events/download_aborted_event_handler.h \
    src/browser/events/download_updated_event_handler.h \
    src/browser/events/favicon_changed_event_handler.h \
    src/browser/events/javascript_dialog_requested_event_args.h \
    src/browser/events/javascript_dialog_requested_event_handler.h \
    src/browser/events/javascript_dialog_type.h \
    src/browser/events/popup_requested_event_args.h \
    src/browser/events/popup_requested_event_handler.h \
    src/browser/events/progress_changed_event_handler.h \
    src/browser/events/reset_requested_event_handler.h \
    src/browser/events/url_event_handler.h \
    src/browser/events/window_closed_event_handler.h \
    src/browser/filters/RequestFilter.h \
    src/browser/filters/RuleFactory.h \
    src/browser/filters/rules/RegexRule.h \
    src/browser/filters/rules/SimplifiedRule.h \
    src/browser/engine/browser_view.h \
    src/browser/engine/qtwebengine_browser_view.h \
    src/browser/engine/wpe_browser_view.h \
    src/browser/memory_pressure_monitor.h \
    src/browser/handlers/ContextMenuHandler.h \
    src/browser/handlers/CookieVisitor.h \
    src/browser/handlers/DialogHandler.h \
    src/browser/handlers/DisplayHandler.h \
    src/browser/handlers/DownloadHandler.h \
    src/browser/handlers/DragHandler.h \
    src/browser/handlers/FocusHandler.h \
    src/browser/handlers/JavaScriptDialogHandler.h \
    src/browser/handlers/KeyboardHandler.h \
    src/browser/handlers/RenderProcessMessageHandler.h \
    src/browser/handlers/RequestHandler.h \
    src/browser/handlers/ResourceHandler.h \
    src/browser/integrations/EdxIntegration.h \
    src/browser/integrations/GenericIntegration.h \
    src/browser/integrations/Integration.h \
    src/browser/integrations/MoodleIntegration.h \
    src/browser/key_generator.h \
    src/browser/request_filter.h \
    src/browser/request_interceptor.h \
    src/browser/responsibilities/BrowserTask.h \
    src/browser/responsibilities/WindowTask.h \
    src/browser/responsibilities/browser/BrowserResponsibility.h \
    src/browser/responsibilities/browser/CacheResponsibility.h \
    src/browser/responsibilities/browser/ConfigurationResponsibility.h \
    src/browser/responsibilities/browser/FileSystemResponsibility.h \
    src/browser/responsibilities/browser/IntegrityResponsibility.h \
    src/browser/responsibilities/browser/WindowHandlingResponsibility.h \
    src/browser/responsibilities/window/ControlResponsibility.h \
    src/browser/responsibilities/window/CookieResponsibility.h \
    src/browser/responsibilities/window/DialogResponsibility.h \
    src/browser/responsibilities/window/DisplayResponsibility.h \
    src/browser/responsibilities/window/DownloadResponsibility.h \
    src/browser/responsibilities/window/KeyboardResponsibility.h \
    src/browser/responsibilities/window/LifeSpanResponsibility.h \
    src/browser/responsibilities/window/RequestResponsibility.h \
    src/browser/responsibilities/window/WindowResponsibility.h \
    src/browser/responsibilities/window/ZoomResponsibility.h \
    src/browser/webengine_environment.h \
    src/browser/wrapper/CefSharpBrowserControl.h \
    src/browser/wrapper/CefSharpPopupControl.h \
    src/browser/wrapper/Extensions.h \
    src/browser/wrapper/ICefSharpControl.h \
    src/browser/wrapper/events/AuthCredentialsEventHandler.h \
    src/browser/wrapper/events/BeforeBrowseEventHandler.h \
    src/browser/wrapper/events/BeforeContextMenuEventHandler.h \
    src/browser/wrapper/events/BeforeDownloadEventHandler.h \
    src/browser/wrapper/events/BeforeUnloadDialogEventHandler.h \
    src/browser/wrapper/events/CanDownloadEventHandler.h \
    src/browser/wrapper/events/ContextCreatedEventHandler.h \
    src/browser/wrapper/events/ContextMenuCommandEventHandler.h \
    src/browser/wrapper/events/ContextMenuDismissedEventHandler.h \
    src/browser/wrapper/events/ContextReleasedEventHandler.h \
    src/browser/wrapper/events/DialogClosedEventHandler.h \
    src/browser/wrapper/events/DownloadUpdatedEventHandler.h \
    src/browser/wrapper/events/DragEnterEventHandler.h \
    src/browser/wrapper/events/DraggableRegionsChangedEventHandler.h \
    src/browser/wrapper/events/FaviconUrlChangedEventHandler.h \
    src/browser/wrapper/events/FileDialogRequestedEventHandler.h \
    src/browser/wrapper/events/FocusedNodeChangedEventHandler.h \
    src/browser/wrapper/events/GenericEventArgs.h \
    src/browser/wrapper/events/GotFocusEventHandler.h \
    src/browser/wrapper/events/JavaScriptDialogEventHandler.h \
    src/browser/wrapper/events/KeyEventHandler.h \
    src/browser/wrapper/events/LoadingProgressChangedEventHandler.h \
    src/browser/wrapper/events/OpenUrlFromTabEventHandler.h \
    src/browser/wrapper/events/PreKeyEventHandler.h \
    src/browser/wrapper/events/ResetDialogStateEventHandler.h \
    src/browser/wrapper/events/ResourceRequestEventArgs.h \
    src/browser/wrapper/events/ResourceRequestEventHandler.h \
    src/browser/wrapper/events/RunContextMenuEventHandler.h \
    src/browser/wrapper/events/SetFocusEventHandler.h \
    src/browser/wrapper/events/TakeFocusEventHandler.h \
    src/browser/wrapper/events/UncaughtExceptionEventHandler.h \
    src/browser/wrapper/handlers/ContextMenuHandlerSwitch.h \
    src/browser/wrapper/handlers/DialogHandlerSwitch.h \
    src/browser/wrapper/handlers/DisplayHandlerSwitch.h \
    src/browser/wrapper/handlers/DownloadHandlerSwitch.h \
    src/browser/wrapper/handlers/DragHandlerSwitch.h \
    src/browser/wrapper/handlers/FocusHandlerSwitch.h \
    src/browser/wrapper/handlers/JavaScriptDialogHandlerSwitch.h \
    src/browser/wrapper/handlers/KeyboardHandlerSwitch.h \
    src/browser/wrapper/handlers/RenderProcessMessageHandlerSwitch.h \
    src/browser/wrapper/handlers/RequestHandlerSwitch.h \
    src/settings/password_container.h \
    src/settings/resource_loader.h \
    src/settings/settings_defaults.h \
    src/settings/settings_mapping.h \
    src/settings/settings_parsing.h \
    src/shell/taskbar/taskbar_model.h \
    src/shell/taskbar/platform/audio_controller.h \
    src/shell/taskbar/platform/battery_controller.h \
    src/shell/taskbar/platform/command_helper.h \
    src/shell/taskbar/platform/keyboard_controller.h \
    src/shell/taskbar/platform/network_controller.h \
    src/shell/taskbar/taskbar_service.h \
    src/ui/taskbar/common/taskbar_button.h \
    src/ui/taskbar/common/taskbar_popup.h \
    src/ui/taskbar/common/taskbar_style.h \
    src/ui/taskbar/controls/application_control.h \
    src/ui/taskbar/controls/audio_control.h \
    src/ui/taskbar/controls/battery_control.h \
    src/ui/taskbar/controls/clock_widget.h \
    src/ui/taskbar/controls/external_application_control.h \
    src/ui/taskbar/controls/keyboard_control.h \
    src/ui/taskbar/controls/network_control.h \
    src/ui/taskbar/controls/notification_control.h \
    src/ui/taskbar/controls/raise_hand_control.h \
    src/ui/taskbar/controls/window_list_popup.h \
    src/ui/taskbar/taskbar_widget.h \
    src/userinterface/contracts/Properties/AssemblyInfo.h \
    src/userinterface/contracts/browser/data/download_item_state.h \
    src/userinterface/contracts/browser/data/javascript_result.h \
    src/userinterface/contracts/browser/events/address_changed_event_handler.h \
    src/userinterface/contracts/browser/events/find_requested_event_handler.h \
    src/userinterface/contracts/browser/events/load_failed_event_handler.h \
    src/userinterface/contracts/browser/events/loading_state_changed_event_handler.h \
    src/userinterface/contracts/browser/events/title_changed_event_handler.h \
    src/userinterface/contracts/browser/i_browser_control.h \
    src/userinterface/contracts/browser/i_browser_window.h \
    src/userinterface/contracts/events/action_requested_event_handler.h \
    src/userinterface/contracts/file_system_dialog/file_system_dialog_result.h \
    src/userinterface/contracts/file_system_dialog/file_system_element.h \
    src/userinterface/contracts/file_system_dialog/file_system_operation.h \
    src/userinterface/contracts/file_system_dialog/i_file_system_dialog.h \
    src/userinterface/contracts/i_progress_indicator.h \
    src/userinterface/contracts/i_user_interface_factory.h \
    src/userinterface/contracts/i_window_guard.h \
    src/userinterface/contracts/message_box/i_message_box.h \
    src/userinterface/contracts/message_box/message_box_action.h \
    src/userinterface/contracts/message_box/message_box_icon.h \
    src/userinterface/contracts/message_box/message_box_result.h \
    src/userinterface/contracts/proctoring/events/cancellation_requested_event_handler.h \
    src/userinterface/contracts/proctoring/events/full_screen_changed_event_handler.h \
    src/userinterface/contracts/proctoring/i_proctoring_control.h \
    src/userinterface/contracts/proctoring/i_proctoring_finalization_dialog.h \
    src/userinterface/contracts/proctoring/i_proctoring_window.h \
    src/userinterface/contracts/shell/events/activator_event_handler.h \
    src/userinterface/contracts/shell/events/quit_button_clicked_event_handler.h \
    src/userinterface/contracts/shell/i_action_center.h \
    src/userinterface/contracts/shell/i_action_center_activator.h \
    src/userinterface/contracts/shell/i_activator.h \
    src/userinterface/contracts/shell/i_application_control.h \
    src/userinterface/contracts/shell/i_notification_control.h \
    src/userinterface/contracts/shell/i_system_control.h \
    src/userinterface/contracts/shell/i_taskbar.h \
    src/userinterface/contracts/shell/i_taskbar_activator.h \
    src/userinterface/contracts/shell/i_taskview.h \
    src/userinterface/contracts/shell/i_taskview_activator.h \
    src/userinterface/contracts/shell/i_termination_activator.h \
    src/userinterface/contracts/shell/i_verificator_activator.h \
    src/userinterface/contracts/shell/location.h \
    src/userinterface/contracts/windows/data/credentials_dialog_purpose.h \
    src/userinterface/contracts/windows/data/credentials_dialog_result.h \
    src/userinterface/contracts/windows/data/exam_selection_dialog_result.h \
    src/userinterface/contracts/windows/data/lock_screen_option.h \
    src/userinterface/contracts/windows/data/lock_screen_result.h \
    src/userinterface/contracts/windows/data/password_dialog_result.h \
    src/userinterface/contracts/windows/data/server_failure_dialog_result.h \
    src/userinterface/contracts/windows/events/window_closed_event_handler.h \
    src/userinterface/contracts/windows/events/window_closing_event_handler.h \
    src/userinterface/contracts/windows/i_credentials_dialog.h \
    src/userinterface/contracts/windows/i_exam_selection_dialog.h \
    src/userinterface/contracts/windows/i_lock_screen.h \
    src/userinterface/contracts/windows/i_password_dialog.h \
    src/userinterface/contracts/windows/i_runtime_window.h \
    src/userinterface/contracts/windows/i_server_failure_dialog.h \
    src/userinterface/contracts/windows/i_splash_screen.h \
    src/userinterface/contracts/windows/i_verificator_overlay.h \
    src/userinterface/contracts/windows/i_window.h \
    src/ui/runtime_window.h \
    src/ui/seb_taskbar.h \
    src/seb_settings.h \
    src/seb_session.h \
    src/browser_window.h

RESOURCES += resources.qrc

target.path = /usr/bin
desktop.files = packaging/linux/safe-exam-browser.desktop
desktop.path = /usr/share/applications
mime.files = packaging/linux/safe-exam-browser.xml
mime.path = /usr/share/mime/packages
metainfo.files = packaging/linux/safe-exam-browser.metainfo.xml
metainfo.path = /usr/share/metainfo
icon.files = assets/icons/safe-exam-browser.png
icon.path = /usr/share/icons/hicolor/256x256/apps
icon64.files = assets/icons/64x64/safe-exam-browser.png
icon64.path = /usr/share/icons/hicolor/64x64/apps
examples.files = examples/minimal-config.json
examples.path = /usr/share/doc/safe-exam-browser/examples

INSTALLS += target desktop mime metainfo icon icon64 examples
